In [2]:
import tensorflow as tf

2024-08-05 11:40:25.804550: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-08-05 11:40:26.812380: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-08-05 11:40:27.102383: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-05 11:40:27.701991: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-05 11:40:27.862444: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-05 11:40:28.841132: I tensorflow/core/platform/cpu_feature_gu

In [3]:
x = tf.ones(shape=(2, 1))
print(x)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [4]:
x = tf.random.normal(shape=(3, 1), mean=0., stddev=1.)
print(x)

tf.Tensor(
[[-0.35097536]
 [-0.97983176]
 [-0.2951381 ]], shape=(3, 1), dtype=float32)


In [6]:
x = tf.random.uniform(shape=(3, 1), minval=0, maxval=1)
print(x)

tf.Tensor(
[[0.7327111 ]
 [0.61163116]
 [0.7614558 ]], shape=(3, 1), dtype=float32)


In [7]:
import numpy as np

# numpy variables are assignabale
x = np.ones(shape=(2, 2))
x[0, 0] = 0.

print(x)

[[0. 1.]
 [1. 1.]]


In [9]:
# TF tensor aren't assignable by default
# x = tf.ones(shape=(2, 2))
# x[0, 0] = 0.