In [6]:
import tensorflow as tf

In [7]:
x = tf.ones(shape=(2, 1))
print(x)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [8]:
x = tf.random.normal(shape=(3, 1), mean=0., stddev=1.)
print(x)

tf.Tensor(
[[ 0.40349168]
 [ 0.5363583 ]
 [-0.27592677]], shape=(3, 1), dtype=float32)


In [9]:
x = tf.random.uniform(shape=(3, 1), minval=0, maxval=1)
print(x)

tf.Tensor(
[[0.3466289 ]
 [0.71248615]
 [0.17563164]], shape=(3, 1), dtype=float32)


In [10]:
import numpy as np

# numpy variables are assignabale
x = np.ones(shape=(2, 2))
x[0, 0] = 0.

print(x)

[[0. 1.]
 [1. 1.]]


In [13]:
# TF tensor aren't assignable by default
# x = tf.ones(shape=(2, 2))
# x[0, 0] = 0.

v = tf.Variable(initial_value=tf.random.normal(shape=(3, 1)))
print(v)

v.assign(tf.ones((3, 1)))
print(v)

v[0, 0].assign(3.)
print(v)

v.assign_add(tf.ones((3, 1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-0.2551751 ],
       [-0.06246244],
       [ 1.3484093 ]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[4.],
       [2.],
       [2.]], dtype=float32)>


In [16]:
a = tf.ones((2, 2))
b = tf.square(a)
c = tf.sqrt(a)
d = b + c
e = tf.matmul(a, b)
a *= d
print(f"a:\n {a},\n b:\n {b},\n c:\n {c},\n d:\n {d},\n e:\n {e}")

a:
 [[2. 2.]
 [2. 2.]],
 b:
 [[1. 1.]
 [1. 1.]],
 c:
 [[1. 1.]
 [1. 1.]],
 d:
 [[2. 2.]
 [2. 2.]],
 e:
 [[2. 2.]
 [2. 2.]]


In [18]:
# Gradient Tape, by default variable get tracked
input_var = tf.Variable(initial_value=3.)
with tf.GradientTape() as tape:
    result = tf.square(input_var)
gradient = tape.gradient(result, input_var)

In [19]:
# Gradient as constant need to be watched
input_const = tf.constant(3.)
with tf.GradientTape() as tape:
    tape.watch(input_const)
    result = tf.square(input_const)
gradient = tape.gradient(result, input_const)

In [20]:
# Tensor is capable of secon order gradient (think relationship between distance, speed, accleration)
time =tf.Variable(0.)
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as inner_tape:
        position = 4.9 * time ** 2
    speed = inner_tape.gradient(position, time)
accleration = outer_tape.gradient(speed, time)