In [2]:
import tensorflow as tf


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/homebrew/lib/python3.11/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/opt/homebrew/lib/python3.11/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/opt/homebrew/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/opt/homebrew/lib/python3.11/site-pack

AttributeError: _ARRAY_API not found

ImportError: numpy.core._multiarray_umath failed to import

ImportError: numpy.core.umath failed to import

In [3]:
x = tf.ones(shape=(2, 1))
print(x)

NameError: name 'tf' is not defined

In [ ]:
x = tf.random.normal(shape=(3, 1), mean=0., stddev=1.)
print(x)

tf.Tensor(
[[ 0.52152866]
 [-0.11035951]
 [-0.701555  ]], shape=(3, 1), dtype=float32)


In [ ]:
x = tf.random.uniform(shape=(3, 1), minval=0, maxval=1)
print(x)

tf.Tensor(
[[0.5169169 ]
 [0.61614823]
 [0.1352185 ]], shape=(3, 1), dtype=float32)


In [ ]:
import numpy as np

# numpy variables are assignabale
x = np.ones(shape=(2, 2))
x[0, 0] = 0.

print(x)

[[0. 1.]
 [1. 1.]]


In [ ]:
# TF tensor aren't assignable by default
# x = tf.ones(shape=(2, 2))
# x[0, 0] = 0.

v = tf.Variable(initial_value=tf.random.normal(shape=(3, 1)))
print(v)

v.assign(tf.ones((3, 1)))
print(v)

v[0, 0].assign(3.)
print(v)

v.assign_add(tf.ones((3, 1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-0.9084251],
       [-1.1275812],
       [-0.2678882]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[4.],
       [2.],
       [2.]], dtype=float32)>


In [ ]:
a = tf.ones((2, 2))
b = tf.square(a)
c = tf.sqrt(a)
d = b + c
e = tf.matmul(a, b)
a *= d
print(f"a:\n {a},\n b:\n {b},\n c:\n {c},\n d:\n {d},\n e:\n {e}")

a:
 [[2. 2.]
 [2. 2.]],
 b:
 [[1. 1.]
 [1. 1.]],
 c:
 [[1. 1.]
 [1. 1.]],
 d:
 [[2. 2.]
 [2. 2.]],
 e:
 [[2. 2.]
 [2. 2.]]


In [ ]:
# Gradient Tape, by default variable get tracked
input_var = tf.Variable(initial_value=3.)
with tf.GradientTape() as tape:
    result = tf.square(input_var)
gradient = tape.gradient(result, input_var)

In [ ]:
# Gradient as constant need to be watched
input_const = tf.constant(3.)
with tf.GradientTape() as tape:
    tape.watch(input_const)
    result = tf.square(input_const)
gradient = tape.gradient(result, input_const)

In [ ]:
# Tensor is capable of secon order gradient (think relationship between distance, speed, accleration)
time =tf.Variable(0.)
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as inner_tape:
        position = 4.9 * time ** 2
    speed = inner_tape.gradient(position, time) 
accleration = outer_tape.gradient(speed, time)